'use client'

import { useActionState, useState } from 'react'

import { updateProfileAction, type ProfileFormState } from '@/server/workspace/actions'

import { Alert, Button, Field, Select, Textarea } from './ui'

/** 常用時區。列表以目標市場為主，值一律為 IANA timezone。 */
const TIMEZONES = [
  { value: 'Asia/Hong_Kong', label: '香港（Asia/Hong_Kong）' },
  { value: 'Asia/Taipei', label: '台北（Asia/Taipei）' },
  { value: 'Asia/Macau', label: '澳門（Asia/Macau）' },
  { value: 'Asia/Singapore', label: '新加坡（Asia/Singapore）' },
  { value: 'Asia/Tokyo', label: '東京（Asia/Tokyo）' },
  { value: 'Asia/Shanghai', label: '上海（Asia/Shanghai）' },
]

type Props = {
  initial: {
    displayName: string
    slug: string
    timezone: string
    bio: string
    contactEmail: string
    contactPhone: string
  }
  publicUrlBase: string
}

export function ProfileForm({ initial, publicUrlBase }: Props) {
  const [state, formAction, isPending] = useActionState<ProfileFormState, FormData>(
    updateProfileAction,
    null,
  )
  const [slug, setSlug] = useState(initial.slug)

  /** bootstrap 產生的網址形如 t-8f3k2p，代表老師尚未自訂。 */
  const isAutoGenerated = /^t-[a-z0-9]{6}$/.test(initial.slug)

  // 老師自訂時區若不在常用清單內，補上以免被靜默改掉
  const timezoneOptions = TIMEZONES.some((t) => t.value === initial.timezone)
    ? TIMEZONES
    : [...TIMEZONES, { value: initial.timezone, label: initial.timezone }]

  return (
    <form action={formAction} className="flex flex-col gap-5" noValidate>
      {state?.error && <Alert tone="error">{state.error}</Alert>}
      {state?.success && <Alert tone="success">公開資料已更新。</Alert>}

      <Field
        label="顯示名稱"
        name="displayName"
        required
        maxLength={80}
        defaultValue={initial.displayName}
        disabled={isPending}
        error={state?.fieldErrors?.displayName}
        hint="學生在公開頁看到的名稱"
      />

      <Field
        label="公開頁網址"
        name="slug"
        required
        value={slug}
        onChange={(e) => setSlug(e.target.value)}
        disabled={isPending}
        error={state?.fieldErrors?.slug}
        autoCapitalize="none"
        autoCorrect="off"
        spellCheck={false}
        hint={
          <>
            只可使用小寫英文字母、數字及連字號。目前連結：
            <span className="break-all font-mono text-ink-muted">
              {publicUrlBase}/book/{slug || '…'}
            </span>
            {/* 註冊時自動產生的隨機網址不好記，明確提示可以改 */}
            {isAutoGenerated && (
              <span className="mt-1 block">
                這是註冊時自動產生的網址，建議改成學生容易記住的名稱。
              </span>
            )}
          </>
        }
      />

      <Select
        label="時區"
        name="timezone"
        required
        defaultValue={initial.timezone}
        disabled={isPending}
        error={state?.fieldErrors?.timezone}
        hint="所有時段都會以此時區顯示給學生"
      >
        {timezoneOptions.map((tz) => (
          <option key={tz.value} value={tz.value}>
            {tz.label}
          </option>
        ))}
      </Select>

      <Textarea
        label="簡介"
        name="bio"
        rows={4}
        maxLength={500}
        defaultValue={initial.bio}
        disabled={isPending}
        hint="選填，最多 500 字"
      />

      <fieldset className="flex flex-col gap-4 rounded-lg border border-line p-4">
        <legend className="px-1 text-sm font-medium text-ink">公開聯絡方式</legend>
        <p className="text-xs text-ink-subtle">
          WhatsApp 號碼用於讓學生提交查詢後直接傳訊息給你。請填可接收 WhatsApp 的號碼，連國家／地區號碼。聯絡電郵可選填。
        </p>

        <Field
          label="聯絡電郵"
          name="contactEmail"
          type="email"
          inputMode="email"
          defaultValue={initial.contactEmail}
          disabled={isPending}
        />

        <Field
          label="老師 WhatsApp 號碼"
          name="contactPhone"
          type="tel"
          inputMode="tel"
          maxLength={40}
          defaultValue={initial.contactPhone}
          hint="例如 +852 9123 4567；發佈預約頁前必須填寫"
          disabled={isPending}
        />
      </fieldset>

      <div>
        <Button type="submit" disabled={isPending}>
          {isPending ? '儲存中…' : '儲存'}
        </Button>
      </div>
    </form>
  )
}
