import Link from 'next/link'
import type { Metadata } from 'next'

import { PublishToggle } from '@/components/publish-toggle'
import { Card } from '@/components/ui'
import { getPublishReadiness } from '@/server/public/queries'
import { requireWorkspaceContext } from '@/server/workspace/context'

export const metadata: Metadata = { title: '分享連結' }

export default async function SharePage() {
  const ctx = await requireWorkspaceContext()
  const readiness = await getPublishReadiness(ctx.workspaceId, ctx.instructorProfileId)

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? ''
  const publicUrl = `${appUrl}/book/${ctx.workspaceSlug}`
  const canPublish = readiness.hasService && readiness.hasSchedule && readiness.hasWhatsApp
  const isAutoGeneratedSlug = /^t-[a-z0-9]{6}$/.test(ctx.workspaceSlug)

  return (
    <div className="flex flex-col gap-5">
      <div>
        <h1 className="text-xl font-semibold text-ink">分享連結</h1>
        <p className="mt-1 text-sm text-ink-muted">
          發佈後，任何人開啟這條連結都可以查看你的空檔並提交預約查詢，毋須註冊。
        </p>
      </div>

      {!canPublish && (
        <Card>
          <h2 className="text-sm font-medium text-ink">發佈前還差這些</h2>
          <ul className="mt-2 flex flex-col gap-1.5 text-sm">
            {!readiness.hasService && (
              <li className="text-ink-muted">
                • 至少一項啟用中的服務 —{' '}
                <Link href="/dashboard/services" className="text-brand underline">
                  前往設定
                </Link>
              </li>
            )}
            {!readiness.hasSchedule && (
              <li className="text-ink-muted">
                • 設定每週開放時間 —{' '}
                <Link href="/dashboard/availability" className="text-brand underline">
                  前往設定
                </Link>
              </li>
            )}
            {!readiness.hasWhatsApp && (
              <li className="text-ink-muted">• 填寫老師 WhatsApp 號碼，讓學生提交後通知你 — <Link href="/dashboard/settings/profile" className="text-brand underline">前往設定</Link></li>
            )}
          </ul>
        </Card>
      )}

      <Card>
        <PublishToggle isPublic={ctx.isPublic} canPublish={canPublish} publicUrl={publicUrl} />
      </Card>

      <Card className="border-brand/20 bg-brand-soft/60">
        <h2 className="text-sm font-semibold text-ink">公開頁網址可以修改</h2>
        <p className="mt-1 text-sm text-ink-muted">
          {isAutoGeneratedSlug
            ? '目前使用系統隨機產生的網址。你現在已可直接分享，也可以改成學生容易記住的名稱。'
            : '你可以隨時更改網址名稱；更改後請記得把新連結重新分享給學生。'}
        </p>
        <Link
          href="/dashboard/settings/profile"
          className="mt-3 inline-flex min-h-10 items-center rounded-xl border border-brand/25 bg-surface px-4 text-sm font-semibold text-brand-strong"
        >
          修改公開頁網址 →
        </Link>
      </Card>

      <Card>
        <h2 className="text-sm font-medium text-ink">預覽</h2>
        <p className="mt-1 text-xs text-ink-subtle">
          {ctx.isPublic
            ? '這是學生會看到的頁面。'
            : '先以老師身分檢查課堂及時段；發佈前學生不能看到。'}
        </p>
        <Link
          href={`/book/${ctx.workspaceSlug}${ctx.isPublic ? '' : '?preview=1'}`}
          className="mt-2 inline-block break-all font-mono text-xs text-brand underline"
        >
          {publicUrl}
        </Link>
      </Card>
    </div>
  )
}
